import math, random
a=input("Enter the float number to rount it:")
print "Round of the given floating point number is:",round(a)
b=input("Enter the number:")
print "Square root of a given number is:",math.sqrt(b)
print "Random number between 0 and 1 is:",random.random()
print "Generate random number between 10 and 500 is:",random.uniform(10,500)
print "Exploring all the math and random functions:"
c=input("Enter the c value:")
d=input("Enter the d value:")
e=[3,6,9,12,15]
print "absolute value of x:",abs(c)
print "ceil value of x:",math.ceil(c)
print "comparison between two numbers:",cmp(c,d)
print "Exponential of x:",math.exp(c)
print "absolute value of x with another function fabs():",math.fabs(c)
print "Floor value of x:",math.floor(c)
print "log value of x:",math.log(c)
print "base 10 logarithm value of x:",math.log10(c)
print "largest number in given list of arguments:",max(c,d,b)
print "Smallest number in given list of arguments:",min(c,d,b)
print "value of modf()function is:",math.modf(c)
print "Power value:",pow(c,d)
print "round of a value with respect to another value:",round(a,d)
print "Square root of the value:",math.sqrt(c)
print "choice of the list z is:",random.choice(e)
print "random range of the number:",random.randrange(100,10000,5)
print "random number:",random.random()
print "seed value of x:",random.seed(c)
print "Shuffle list:",random.shuffle(e)
print "generate a random number:",random.uniform(c,d)
