import math
import random
a=input("Enter the float number to rount it:")
print "Round of the given floating point number is:",round(a)
b=input("Enter the number:")
print "Square root of a given number is:",math.sqrt(b)
print "Random number between 0 and 1 is:",random.random()
print "Generate random number between 10 and 500 is:",random.uniform(10,500)
print "Exploring all the math and random functions:"
x=input("Enter the X value:")
y=input("Enter the Y value:")
z=[3,6,7,8,9]
print "absolute value of x:",abs(x)
print "ceil value of x:",math.ceil(x)
print "comparison between two numbers:",cmp(x,y)
print "Exponential of x:",math.exp(x)
print "absolute value of x with another function fabs():",math.fabs(x)
print "Floor value of x:",math.floor(x)
print "log value of x:",math.log(x)
print "base 10 logarithm value of x:",math.log10(x)
print "largest number in given list of arguments:",max(x,y,b)
print "Smallest number in given list of arguments:",min(x,y,b)
print "value of modf()function is:",math.modf(x)
print "Power value:",pow(x,y)
print "round of a value with respect to another value:",round(a,y)
print "Square root of the value:",math.sqrt(x)
print "choice of the list z is:",random.choice(z)
print "random range of the number:",random.randrange(100,10000,5)
print "random number:",random.random()
print "seed value of x:",random.seed(x)
print "Shuffle list:",random.shuffle(z)
print "generate a random number:",random.uniform(x,y)
